version: "3"

secrets:
  red_discord_token:
    file: red_discord_token

services:
  red:
    image: djfdyuruiry/red-discord-server:latest
    volumes:
      - ${PWD}/red:/home/red/.local/share/Red-DiscordBot
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: Europe/Dublin
      LANG: en_IE
      INSTANCE_NAME: my_instance
      PREFIX: "!"
    secrets:
      - red_discord_token
