#! /usr/bin/env bash
set -Eeuo pipefail

function main() {
  local setupFilePath="${RED_DATA_PATH}/.setup"

  if [ ! -f "${setupFilePath}" ]; then
    pipenv run ./bin/setup "${INSTANCE_NAME}" "${PREFIX}"

    touch "${setupFilePath}"
  fi

  pipenv run redbot "${INSTANCE_NAME}"
}

main
